#!/usr/bin/env python

import os
import json


INPUT = ["src/default_custom.json", "src/default.json"]
OUTPUT = "lib/Config/default.h"

TEMPLATE = """
// DO NOT EDIT
//
// This file is autogenerated!

#define DEFAULT_CONFIG "%(cfg)s"
"""


input_file = INPUT[-1]


for fname in INPUT:
    if (os.path.exists(fname)):
        input_file = fname
        break


with open("src/default.json", "r") as fn:
    parsed = json.load(fn)

    data = TEMPLATE % {"cfg": json.dumps(
        parsed, separators=(',', ':')).replace('"', '\\"')}

    with open(OUTPUT, "w+") as fo:
        fo.write(data)
